Feature/subscription frontend
webplatformz/quiz pull request #13
Opened 2019-04-08 13:57 UTC by andmue

2019-04-08 14:04 UTC, mleimer submitted a review, later dismissed

2019-04-08 14:22 UTC, mleimer commented on frontend/src/components/pages/start/Join.tsx
> +                           pattern="-?[0-9]*(\.[0-9]+)?"
Die QuizId erlaubt andere Zeichen [a-z] und [0-9]

2019-04-08 14:25 UTC, mleimer commented on frontend/src/components/pages/start/Join.tsx
> +                           pattern="-?[0-9]*(\.[0-9]+)?"
Mit https://github.com/webplatformz/quiz/pull/14 gelten jedoch andere Werte

2019-04-08 14:27 UTC, danielsuter requested changes

2019-04-08 14:27 UTC, danielsuter commented on frontend/src/components/pages/quiz/WaitingRoom.tsx
> +export default class WaitingRoom extends Component<any, any> {
why not use shorthand syntax?

2019-04-08 14:27 UTC, danielsuter commented on frontend/src/components/pages/start/Create.tsx
> +export default class Create extends Component<any, any> {
why not use shorthand syntax?

2019-04-08 14:27 UTC, danielsuter commented on frontend/src/components/pages/start/Join.tsx
> +    state = {
use types

2019-04-08 14:27 UTC, danielsuter commented on frontend/src/components/pages/start/Join.tsx
> +    constructor(props: any) {
use types

2019-04-08 14:27 UTC, danielsuter commented on frontend/src/components/pages/start/Join.tsx
> +                    nickname: this.state.nickname
nickname is not defined

2019-04-08 14:27 UTC, danielsuter commented on frontend/src/components/pages/start/Join.tsx
> +                <Textfield onChange={(e: any) => {this.setState({...this.state, joinId: e.target.value})}}
type e

2019-04-08 14:27 UTC, danielsuter commented on frontend/src/components/pages/start/Join.tsx
> +                <Textfield onChange={(e: any) => {this.setState({...this.state, nickname: e.target.value})}}
type Event

2019-04-08 14:27 UTC, danielsuter commented on frontend/src/components/pages/start/Start.tsx
> +export default class Start extends Component<any, any> {
use shorthand syntax

2019-04-08 14:27 UTC, danielsuter commented on server/domain/player.ts
> +    constructor(public id: number, public name: string, public score: number) {
use string instead of number

2019-04-09 06:11 UTC, mleimer commented on frontend/src/components/pages/start/Join.tsx
> +                           pattern="-?[0-9]*(\.[0-9]+)?"
ALLOWED_CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghkmnpqrstuvwxyz123456789";

2019-04-09 06:23 UTC, mleimer approved these changes

2019-04-09 06:31 UTC, merged