Remove dead code.
webplatformz/quiz pull request #18
Opened 2019-04-09 12:09 UTC by danielsuter

2019-04-09 12:44 UTC, mleimer requested changes

2019-04-09 12:44 UTC, mleimer commented on server/game/game.spec.ts
> -    game.joinAsOperator('Big Boss');
Diese Zeile bitte nicht löschen. Ein Operator-Join soll den CB ja nicht triggern.

2019-04-09 13:03 UTC, mleimer approved these changes

2019-04-10 05:52 UTC, danielsuter commented on server/game/game.spec.ts
> -    game.joinAsOperator('Big Boss');
Methode existiert nicht mehr.

2019-04-10 06:06 UTC, merged